apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: srjnm
  labels:
    component: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: srjnm/api-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: COUNTER_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: counter-url
        - name: CONVERTER_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: converter-url

          
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: srjnm
  labels:
    component: api
spec:
  selector:
    app: api-converter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080