apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  namespace: srjnm
  labels:
    component: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: ghcr.io/adyanth/docker-k8s-final-assessment:converter-latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVE_PATH
          value: "convert"
        - name: PART_OF
          valueFrom:
            configMapKeyRef:
              name: config
              key: part-of
          
---
apiVersion: v1
kind: Service
metadata:
  name: service-converter
  namespace: srjnm
  labels:
    component: converter
spec:
  selector:
    app: converter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080