apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-volume
  namespace: srjnm
  labels:
    component: volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"